### PR TITLE
AutoDownload for the Player. Refactoring of the form

### PR DESCRIPTION
**Pull request by Belphemur**
A lot of change in the code of the UpdateCheckerForm to reach this.

# New features

0. SplitButton for new Player Update
0. Remembering last choice made when using the splitbutton for the player updates. It means the user have to only use once the Menu of the SplitButton, after that it will always download the same release when simply clicking the button.
0. File download is cancellable and clean the leftover file automatically.
0. One real form used for Update with couple of virtual method to make a ExtensionForm too.

### CODE REVIEW

**Comment by zachsaw** [comment]
Nice!

**Comment by Belphemur** [comment]
I would like to improve it slightly for the default behavior of the Player Update SplitButton.

How can I get the version of MPDN launched ? I mean the architecture for which MPDN has been built ?

With this, I could default the download button to select that automatically when the SplitButton is not used the first time (instead of the arch of the OS).

**Comment by zachsaw** [comment]
Use this.

     Assembly.GetEntryAssembly().GetName().ProcessorArchitecture ==
                    ProcessorArchitecture.MSIL
                    ? "AnyCPU"
                    : Environment.Is64BitProcess ? "64Bit" : "32Bit";

**Comment by Belphemur** [comment]
Thanks !
I did find the ProcessorArchitecture, but never from which Assembly I had to retrieve it.
I pushed it, going to make the pull request.

With this, I'm really happy with the feature !

**Pull request merged**
