### PR TITLE
Extension enhancements

### PR DESCRIPTION
**Pull request by Garteal**
One playlist commit snuck in, but what the heck.

Playlist:
 - Refactoring and prevent regex window from closing settings
 - Changed the behavior of the "Close" button to also save the
   changes in addition to closing
 - Removed "apply" button and added a "clear" button instead for
   convenience

GoToTime
 - Added set current media position & minor cosmetic changes for GoToTime

MediaInfo
 - Style up MediaInfo dialog and added MPDN icon

### CODE REVIEW

**Comment by zachsaw** [comment]
Ah I just released v1.10.0...

**Comment by Ryrynz** [comment]
:'3

**Comment by Belphemur** [comment]
1.10.1 ? :+1:

**Comment by Garteal** [comment]
Sorry, saw you made a release when I checked out GitHub and saw I was too late anyway. But before you do a new release, let me fix some minor things quickly.

**Comment by zachsaw** [comment]
I might wait until there's more changes before I make a new release. Otherwise the update checker only shows the latest release changelog... another issue coming up @Belphemur :)

**Comment by zachsaw** [comment]
I've added you both (@Garteal and @Belphemur) as collaborators. You can now merge PRs.

**Pull request merged**
