### PR TITLE
[WIP] Remove "Chain.Intialize()" and "Chain.Reset()"

### PR DESCRIPTION
**Pull request by Shiandow**
Also fix some minor issues that made ScriptGroup hotkeys slower than necessary.

Switching renderscripts is still a bit sluggish though. Not sure why.

### CODE REVIEW

**Comment by zachsaw** [comment]
Haven't had time to look at the changes yet but, Merry Christmas mate! :)

**Comment by Shiandow** [comment]
You're still a bit too early here ;-) but Merry Christmas! 

Just look at the changes whenever you have time, no rush.

**Comment by Shiandow** [comment]
And a happy new year as well!

**Comment by zachsaw** [comment]
Happy new year! Can't believe it's already 2016!

**Comment by Shiandow** [comment]
I think I figured out why hotkeys were so sluggish. I forgot to set "Handled" to true in the OnKeyDown event. Not sure why it caused such a big delay, though.

**Pull request merged**
