### PR TITLE
[Work in Progress] Make AudioChain use Filters

### PR DESCRIPTION
**Pull request by Shiandow**
The best way I could find to make this work was to convert "AudioChain"
into a Filter and wrap a Chain around that.

This makes it slightly harder to handle settings, although
on the flip side you can now assume that settings remain constant

Haven't figured out how to connect the "Process" function to the "Render()"
function though, I'm not entirely sure what information is supposed to
go where. I'm pretty sure everything that's necessary is there though.

Apart from that the Example scripts are more or less done, and the
DynamicRangeCompressor should be more or less finished as well (I hope).

### CODE REVIEW

**Comment by zachsaw** [comment]
I'll take a look at the changes when I get some time. A bit busy at the moment.

**Comment by Shiandow** [comment]
Okay. I'll see if I can figure out how to get things working (or at least compilable) in the meantime. It's ~~possible~~ likely that I overlooked something though.

**Comment by Shiandow** [comment]
By the way, is "AudioChain.Reset" supposed to be called when the filter chain is disposed? Or should it be called every time the filter chain is reset?

**Comment by Shiandow** [comment]
By the way, I added the "PinFilter" class that allows filters to be connected to their input afterwards. This makes it possible to make Filters with parameterless constructors that can easily be made into Chains. I'd really like your opinion on that construction, since it is a bit of 'hack'.

Unfortunately this construction doesn't work entirely If the Filter needs any settings, you need to pass those manually. This is what I did with the DynamicRangeCompressor.

**Pull request merged**
