### PR TITLE
Extended playlist

### PR DESCRIPTION
**Pull request by Garteal**
Here it finally is. I've been refactoring and testing for the last couple of days so hopefully I didn't miss anything. I will post a bit more info on it in the forum thread once it has been reviewed and merged.

### CODE REVIEW

**Comment by zachsaw** [comment]
I'll review and test and if everything is OK I'll merge the PR.

**Comment by zachsaw** [comment]
Well done! Works brilliantly and love the UI!
Found a couple of minor problems which I'll quickly fix up after I merge the PR - the form goes behind MPDN's main form when it's set to always on top, and when MPDN window is snapped to the lower right corner of the desktop, the playlist form opens up almost outside of the desktop bounds.

BTW, any plans to support drag / drop re-order & add media files?

**Comment by Garteal** [comment]
Haven't used always on top so I wasn't aware of the issue. The window going OoB I forget to check for heh. I could do a quick fix and PR for it if you want.

Drag and drop adding and reordering sounds like a good idea to me.

**Comment by zachsaw** [comment]
Yeah I'd appreciate it if you could do a quick fix and PR.
I'll let you know how to fix that always on top issue in a while - I'm gonna do a quick test to see what is needed to fix it in the most elegant way.

**Comment by zachsaw** [comment]
Oh btw, would you mind if I put the resx file generated from your resources file in the repository (outside of Extensions folder, probably in a folder called "src")? Without the resx file, other devs won't be able to open the extension in their IDE and they won't be able to compile the whole extension repository into an assembly to test their own extensions either.

**Comment by Garteal** [comment]
No problem at all. I'll commit the resx file as well then when things change up in there.
I'll make a PR for the OoB and you can comment there for your fix while I'll play around and see how far I get with it.

**Comment by zachsaw** [comment]
Ah ok I found the problem... I'll quickly add the resx file and fix the always on top issue now, if you don't mind waiting. Won't be long.

**Comment by Garteal** [comment]
Sure, go ahead. PR'd the out of bounds just there.

**Comment by zachsaw** [comment]
OK I've just committed the changes.

**Pull request merged**
