### PR TITLE
Adding a FileDownloader for Extensions

### PR DESCRIPTION
**Pull request by Belphemur**
Can be later used also for the UpdateChecker of the player. But I would like some feedback on this code before doing the same for the Player.

### CODE REVIEW

**Comment by Shiandow** [comment]
Just gave it a try. Looks nice! Although I would appreciate a way to only check updates for the player. I also liked the way you can choose for either the installer or the zip file, it would be nice if that change was also added to the player UpdateChecker.

**Comment by Belphemur** [comment]
Thanks for the feedback !

Do you think I should add another button in the Player Update Checker to be redirected to the Website and use also a splitbutton for choosing which version to download ? By default it would select the installer of the current used Architecture. Once used once, it will remember the last choice and clicking on the Button will default to that last choice.

I could also simply add a hyperlink to the website. Or I can add in the SplitButton the option Manually that would then do the same as the current Download Button. This way the user can still choose what he prefers !

**Comment by Shiandow** [comment]
I think the cleanest way is to add an "Open in browser" option to the SplitButton. But I'm not 100% sure if that is the best option. I think most programs add it as an hyperlink somewhere, if at all.

**Comment by zachsaw** [comment]
I like Shiandow's idea of "Open in browser..." in the SplitButton drop down. Bring them straight to GitHub's release page and if they wanted an older version, they can download it from there. Otherwise the latest .exe and .zip would suffice.

By the way, is there a way to cancel the file download when user has hit the cancel button?

**Comment by Belphemur** [comment]
Okay I'll add a Open in Browser as last option in the SplitButton. I'll refactor the code to make only one form that'll work for both Updates.

For now it's not possible to cancel the download. That's my first priority now :)

Again thank you both for the feedback!

On 9 juillet 2015 06:07:47 EEST, Zach Saw <notifications@github.com> wrote:
>I like Shiandow's idea of "Open in browser..." in the SplitButton drop
>down. Bring them straight to GitHub's release page and if they wanted
>an older version, they can download it from there. Otherwise the latest
>.exe and .zip would suffice.
>
>By the way, is there a way to cancel the file download when user has
>hit the cancel button?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zachsaw/MPDN_Extensions/pull/66#issuecomment-119801109

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zachsaw** [comment]
Look forward to the auto download for the player too. I have 4 systems at home that I currently manually update so this will save me some time! Good work mate!

**Comment by Belphemur** [comment]
I have the cancel download that works now. 
I'm in the middle of the refactoring to have only one form for Both the Player and Extension.

**Pull request merged**
