### PR TITLE
Fix incorrect project file

### PR DESCRIPTION
**Pull request by Belphemur**
The RESX where present in the file but not in the folder

VS Community 2013 complains about it when trying to build the solution.

### CODE REVIEW

**Comment by Shiandow** [comment]
Any particular reason you copied the PlayerExtensions/Resources folder to the Sources folder?.

**Comment by zachsaw** [comment]
VS2013 automatically recreates the .resx file when you open its corresponding form, unless it's already in the project file but is missing (which is the case here). Any suggestions how to automate the handling of resx files?

**Comment by zachsaw** [comment]
I've removed the unnecessary resx files from the project and also made `make.bat` delete them as part of the build process. It can only go as far as to give you an error when it builds to let you know the resx files are missing. You'll still have to delete them manually from the project. It would be good if VS could be told not to auto generate resx files unless we tell it to.

**Comment by Belphemur** [comment]
@Shiandow Oups, must be a leftover before the change of structure. I thought I removed everything.

@zachsaw Thanks for this. But with the change you made to the autocrlf, I can't contribute to the project any more if I don't commit all the file in the commit "Fix encoding". I tried everything, disable autocrlf for the project, deleted all the file, checkout, etc ... everytime after the checkout git is telling me the files are modified.

**Comment by Garteal** [comment]
^ getting this too in my forks. Kinda annoying tbh. I'm synced with master yet there's still modified files. Can't switch branches without committing first (haven't pushed em yet).

**Comment by Shiandow** [comment]
As far as I know it's because the line ending changed again. Best solution I've found so far is to follow [this guide](https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings) to fix all files at once. Not sure if there's a better method.

**Comment by Belphemur** [comment]
For now I activated the autocrlf and now it does work without problem (only the Assembly was conflicting and the update checker)

Since I worked on the update checker I took the time to commit it.

**Comment by zachsaw** [comment]
I've done the fix recommended in the guide. Can you let me know if it's fixed on your end?

**Comment by Belphemur** [comment]
I confirmed your fix corrected the problem for me :+1: 
I just had to delete manually the conflicted file, merge then checkout the deleted file.

**Comment by Garteal** [comment]
Same here. Thanks Zachs.

**Pull request closed without merging**
