### PR TITLE
Rework "MakeFilter" and some other status improvements.

### PR DESCRIPTION
**Pull request by Shiandow**

### CODE REVIEW

**Comment by zachsaw** [comment]
Hmm the Youtube extension looks interesting! :)

**Comment by Shiandow** [comment]
Ah, that one wasn't supposed to be in there...

That said it works reasonably well, you just need to be sure to put youtube-dl.exe somewhere where it can find it.

**Comment by Shiandow** [comment]
Haven't really had time to make it 'user friendly' though.

**Comment by zachsaw** [comment]
Might want to include the exe in the distribution. I'm surprised it's even possible! But that's something I'd definitely use. Does it do YouTube playlist too?

**Comment by zachsaw** [comment]
BTW I'll remove RenderChainDescription static class and make the player extension get the status text from the active render script. RenderChain probably needs a StatusText property.

**Comment by zachsaw** [comment]
Haven't actually tried the YouTube extension yet but does it only start playing when the file is fully downloaded?

**Comment by Shiandow** [comment]
Yeah, haven't found a way to stream files yet, so it downloads them entirely. In fact if you have ffdshow installed it will download audio and video separately and merge them later, so you kind of have to. That part can be prevented though.

To make it play a link, you need to drag the url to MPDN and it will play it. Although it doesn't check if it's a youtube link, which isn't too nice when the url is a link to a file.

So yeah, it's not really 'polished' yet. It only works well enough for my purposes.

Haven't a clue what it will do with playlists. It might download the entire playlist.

**Comment by zachsaw** [comment]
Ah OK. I think we should remove it from repository then at least until it's user friendly enough.

**Comment by Shiandow** [comment]
Maybe give it it's own branch? I think there's a lot of small things that might need to be done until it's user friendly, so it would help if others could work on improving it.

**Comment by zachsaw** [comment]
Yup good idea.

**Pull request merged**
